kind: Service
apiVersion: v1
metadata:
  name: webapi
spec:
  selector:
    app: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: gcr.io/YOUR_PROJECT_ID/webapi:${SHORT_SHA}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
